repos:
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        name: black (python formatter)
        language_version: python3
        types: [python]
        additional_dependencies: []
